# cpl/models.py
from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class CPLNode:
    """CPL脚本中的单个STEP节点"""
    step_number: int
    label: str                              # STEP描述，如 "生成病历"
    task_id: str                            # 关联的Task ID
    task_type: str                          # 关联的TaskType值
    body_lines: list[str] = field(default_factory=list)   # 该STEP内的CPL代码行
    depends_on: list[str] = field(default_factory=list)    # 依赖的task_id列表

    def render(self, indent: str = "    ") -> str:
        """渲染为CPL STEP文本块"""
        lines = [f'{indent}STEP {self.step_number} "{self.label}":']
        for line in self.body_lines:
            lines.append(f"{indent}{indent}{line}")
        return "\n".join(lines)


@dataclass
class CPLScript:
    """完整CPL脚本的结构化表示"""
    pathway_name: str
    generated_at: str = field(default_factory=lambda: datetime.now().strftime("%Y-%m-%d %H:%M"))
    header_comments: list[str] = field(default_factory=list)
    asserts: list[str] = field(default_factory=list)        # ASSERT语句
    nodes: list[CPLNode] = field(default_factory=list)       # STEP节点列表
    epilogue_lines: list[str] = field(default_factory=list)  # 归档/日志等收尾语句

    def render(self, indent: str = "    ") -> str:
        """渲染完整CPL脚本文本"""
        parts = []

        # 头部注释
        parts.append("# AutoCLP CPL Script")
        parts.append(f"# Generated by: CPL Generator")
        parts.append(f"# Date: {self.generated_at}")
        for c in self.header_comments:
            parts.append(f"# {c}")
        parts.append("")

        # PATHWAY 块
        parts.append(f'PATHWAY "{self.pathway_name}":')
        parts.append("")

        # ASSERT
        if self.asserts:
            parts.append(f"{indent}# ---- 前置断言 ----")
            for a in self.asserts:
                parts.append(f"{indent}{a}")
            parts.append("")

        # STEP 节点
        for node in self.nodes:
            parts.append(node.render(indent))
            parts.append("")

        # 收尾
        if self.epilogue_lines:
            parts.append(f"{indent}# ---- 收尾 ----")
            for line in self.epilogue_lines:
                parts.append(f"{indent}{line}")
            parts.append("")

        return "\n".join(parts)
